fastlane_version "1.106.2"

default_platform :ios

lane :update do
  xcodeproj = "SettingsBundleExample/SettingsBundleExample.xcodeproj"

  increment_build_number xcodeproj: xcodeproj
  update_settings_bundle xcodeproj: xcodeproj, key: "CurrentAppVersion"
end
