min_fastlane_version "2.69.0"
default_platform :ios
import_actionspace(:settings_bundle, as: :sb)

desc "Test lane to update SettingsBundleExample"
lane :test do
  xcodeproj = "examples/SettingsBundleExample/SettingsBundleExample.xcodeproj"

  increment_build_number xcodeproj: xcodeproj
  sb.update xcodeproj: xcodeproj,
                       key: "CurrentAppVersion",
                       value: ":version (:build)"
  sb.update xcodeproj: xcodeproj,
                       key: "BuildDate",
                       value: Time.now.strftime("%B %-d, %Y")

  # Uncomment to commit these changes.
  # commit_version_bump xcodeproj: xcodeproj
end

desc "Test lane to update SettingsBundleGroupExample"
lane :group_test do
  xcodeproj = "examples/SettingsBundleGroupExample/SettingsBundleGroupExample.xcodeproj"

  increment_build_number xcodeproj: xcodeproj
  sb.update xcodeproj: xcodeproj,
                       key: "CurrentAppVersion",
                       value: ":version (:build)"
  sb.update xcodeproj: xcodeproj,
                       key: "BuildDate",
                       value: Time.now.strftime("%B %-d, %Y")

  # Uncomment to commit these changes.
  # commit_version_bump xcodeproj: xcodeproj
end

desc "Test lane to update SettingsBundleLibraryExample"
lane :library_test do
  xcodeproj = "examples/SettingsBundleLibraryExample/SettingsBundleLibraryExample.xcodeproj"
  # Rather than passing the xcodeproj argument to all invocations of update_settings_bundle
  ENV["SETTINGS_BUNDLE_XCODEPROJ"] = xcodeproj

  increment_build_number xcodeproj: xcodeproj
  sb.update target: "SettingsBundleLibraryExample",
            key: "CurrentAppVersion",
            value: ":version (:build)"
  sb.update target: "SettingsBundleExampleFramework",
            key: "CurrentFrameworkVersion",
            value: ":version (:build)",
            file: "Framework.plist"
  sb.update key: "BuildDate",
            value: Time.now.strftime("%B %-d, %Y")

  # Uncomment to commit these changes.
  # commit_version_bump xcodeproj: xcodeproj
end

import "Fastfile.internal"
